wizelineacademy/itesm-socioformador-ago-dec-2023-team-02

- apps/web/lib/conversation.ts
- apps/web/lib/prisma.ts
> chore: 🤖 created conversation endpoints

- apps/web/lib/model.ts
> chore: 🤖 created model endpoints

- apps/web/lib/model.ts
> chore: 🤖 updated import of primsa to type import

- apps/web/lib/conversation.ts
> test: 💍 Added validation to endpoints

- apps/web/lib/tag.ts
Creates functions that make use of prisma client and that allow CRUD operations on the Tag model. Thorough testing is yet to be done for the functions, with a populated database.
> chore: 🤖 Define prisma client queries for the Tag model

- apps/web/lib/model.ts
- apps/web/lib/provider.ts
> chore: 🤖 Created provider methods for endpoints

- apps/web/lib/conversation.ts
> test: 💍 Added deactivate and delete conversation methods

- apps/web/lib/tag.ts
- apps/web/lib/user.ts
- apps/web/lib/utils.ts
- apps/web/types/PrismaClientTypes.ts
Creates reading and deletion queries for the User model, updates the return type of Tag queries, defines the interface GlobalParameters.
Thorough testing of the queries is yet to be done with a populated database.
> chore: 🤖 Creates reading, deletion queries for the User model

- apps/web/lib/conversation.ts
- apps/web/lib/message.ts
- apps/web/lib/model.ts
- apps/web/lib/provider.ts
- apps/web/lib/tag.ts
- apps/web/lib/user.ts
- apps/web/lib/utils.ts
- apps/web/types/prisma-client-types.ts
Creates prisma client query methods for the User model, makes minor changes to the query methods of Tag.
Testing is yet to be done with a populated database. Further validation of input data could be added.
> chore: 🤖 Create prisma client queries for the User model

- CODE_OF_CONDUCT.md
Create a Code of Conduct based on Mozilla Code of Conduct guidelines.
> feat(app): Created a CODE_OF_CONDUCT.md file

- apps/web/app/api/conversations/[id]/route.ts
- apps/web/app/api/conversations/route.ts
- apps/web/app/api/providers/[id]/route.ts
- apps/web/app/api/providers/route.ts
- apps/web/app/api/schema.md
- apps/web/app/page.tsx
- packages/eslint-config-custom/next.js
Implemented model schema inspired of entity relationship diagram.
✅ Closes: #21
> chore: 🤖 Implemented schema for API

- apps/web/lib/conversation.ts
- apps/web/lib/prisma-input-validation.ts
- apps/web/lib/tag.ts
- apps/web/lib/user.ts
- apps/web/types/model-parameters-types.ts
- apps/web/types/prisma-client-types.ts
Implements prisma client queries in Conversation and User to directly update model parameters.
> chore: 🤖 Implement queries to update model params

- apps/web/app/api/messages/[id]/route.ts
- apps/web/app/api/messages/conversation/[id]/route.ts
- apps/web/app/api/messages/route.ts
- apps/web/lib/message.ts
> chore: 🤖 Created api routes of messages

- apps/web/lib/conversation.ts
> chore: 🤖 Created functionality to update parameters

- apps/web/app/api/users/[id]/route.ts
- apps/web/app/api/users/route.ts
- apps/web/lib/user.ts
- apps/web/types/user-types.ts
Defines api routes for the edition, deletion, and creation of users.
> chore: 🤖 Implements api routes related to the User model

- apps/web/app/api/tags/[id]/route.ts
- apps/web/app/api/tags/conversation/[id]/route.ts
- apps/web/app/api/tags/route.ts
- apps/web/app/api/tags/user/[id]/route.ts
- apps/web/lib/tag.ts
- apps/web/types/tag-types.ts
Creates route handlers for the addition, deletion, retrieval, and modification of the Tag model
> chore: 🤖 Implement api routes related to the Tag model

- apps/web/app/(root)/(user)/conversation/layout.tsx
- apps/web/components/user/conversationSidebar/molecules/left-sidebar.tsx
Modifies the structure of the components directory, placing interface sections at the first level of components
> chore: 🤖 Restructure the components directory

- apps/web/data/models-data.ts
- apps/web/lib/conversation.ts
- apps/web/lib/helper/storage/delete-image.ts
Implemented functionality to delete images from S3 when a conversation is deleted
> chore: 🤖 Implemented image deletion

- apps/web/components/admin/groupBody/molecules/group-header.tsx
- apps/web/components/admin/groupSidebar/organisms/group-sidebar.tsx
> style: 💄 Styled group sidebar

- apps/web/components/shared/molecules/general.tsx
- apps/web/components/theme-button.tsx
- apps/web/components/user/conversationSidebar/organisms/conversation-sidebar.tsx
> style: 💄 Styled settings menu

- apps/web/components/admin/groupBody/molecules/group-header.tsx
- apps/web/components/admin/groupBody/molecules/group-table.tsx
- apps/web/components/admin/groupBody/organisms/group-body.tsx
> style: 💄 Style group body

- apps/web/lib/helper/gpt/credits-and-tokens.ts
Created function to calculate the number of tokens using credits, as well as the amount of images that can be generated with an amount of credits
> chore: 🤖 Created function to calculate tokens from credits

- apps/web/components/admin/groupBody/organisms/group-body.tsx
- apps/web/components/shared/molecules/text-description-modal.tsx
- apps/web/helpers/group-helpers.ts
- apps/web/helpers/string-helpers.ts
> chore: 🤖 Add documentation to string and group helper functions

- .github/workflows/cicd.yml
- .github/workflows/release.yml
- apps/web/components/admin/groupBody/molecules/group-table.tsx
- apps/web/components/admin/groupBody/organisms/group-body.tsx
- apps/web/components/admin/modals/add-user-modal.tsx
- apps/web/components/shared/molecules/global-context.tsx
- apps/web/components/user/conversationHeader/molecules/modal-gpt-parameters.tsx
- apps/web/components/user/conversationHeader/molecules/model-card.tsx
- apps/web/components/user/newConversation/atoms/model-selection-card.tsx
- apps/web/next.config.js
- turbo.json
> ci: 🎡 Prepare to release

- apps/web/lib/user.ts
Fix failure to decrement an individual user's credits when the amount to decrement is greater than the user's current remaining credits.
> fix: 🐛 Fix failure to decrement user credits

- apps/web/components/shared/molecules/confirm-delete-modal.tsx
> style: 💄 Styled modal

- apps/web/components/user/newConversation/organism/welcome.tsx
> style: 💄 centered text
